import './globals.css'
import { Inter } from 'next/font/google'
import React from "react";
import AppTheme from "./AppTheme";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <AppTheme >
            <body className={inter.className}>
                {children}
            </body>
        </AppTheme>
    </html>
  )
}
